tableHeader <- c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
electricData <- read.table("household_power_consumption.txt", sep=";", col.names=tableHeader, skip=66637, nrows=2880)
daysOfWeek <- c("Thu", "Fri", "Sat")
plot(electricData$Global_active_power, type="l", ylab="Global Active Power (kilowatts)", xaxt="n")
axis(1, at=1:3, labels=daysOfWeek[1:3])
dev.print(png, filename = 'plot2.png', width = 480, height = 480) 